name: CI pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      
    - name: docker
      uses: docker/setup-buildx-action@v3
      
    - name: test and build
      run: |
        cargo test
        docker build -t currc:latest .
        